# Generated by Django 2.0.7 on 2018-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_vote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vote_number',
            field=models.IntegerField(default=0, verbose_name='投票數'),
        ),
    ]
