# Generated by Django 2.0.7 on 2018-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180806_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vote_number',
            field=models.PositiveIntegerField(default=0, verbose_name='投票數'),
        ),
    ]
