# Generated by Django 2.0.7 on 2018-08-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20180805_2131'),
        ('account', '0004_auto_20180806_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assess_progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment'),
        ),
    ]
