# Generated by Django 2.0.7 on 2018-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_course_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='static/account/images/bug.jpg'),
        ),
    ]
