# Generated by Django 2.0.7 on 2018-08-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180812_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='account/images/bug.jpg'),
        ),
    ]
