# Generated by Django 2.0.7 on 2018-08-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180812_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(default='account/images/bug.jpg'),
        ),
    ]
