# Generated by Django 2.0.7 on 2018-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180812_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.TextField(default='media/user_images/default/bug.png'),
        ),
    ]
