# Generated by Django 2.0.7 on 2018-11-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20181112_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.URLField()),
            ],
        ),
    ]
