# Generated by Django 2.0.7 on 2018-11-14 02:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
