# Generated by Django 2.0.7 on 2018-11-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_achievement_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement_get',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Achievement'),
        ),
    ]
