# Generated by Django 2.0.7 on 2018-12-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20181202_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_commentable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achievement_get',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Achievement'),
        ),
    ]
