# Generated by Django 2.0.7 on 2018-10-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isImage',
            field=models.BooleanField(default=False),
        ),
    ]
