# Generated by Django 2.0.7 on 2018-10-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_content_isimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
