# Generated by Django 2.0.7 on 2018-07-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0005_auto_20180723_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='havevote',
            name='ass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='havevote',
            unique_together={('user', 'ass')},
        ),
    ]
