# Generated by Django 2.0.7 on 2018-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_assessmentcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcode',
            name='code',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
