# Generated by Django 2.0.7 on 2018-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_havelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcode',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
