# Generated by Django 2.0.7 on 2018-09-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_assessmentcode_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcode',
            name='code',
            field=models.TextField(max_length=15000, null=True),
        ),
    ]
