# Generated by Django 2.0.7 on 2018-09-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_auto_20180911_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcode',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
