# Generated by Django 2.0.7 on 2018-11-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0027_auto_20181108_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='havevote',
            unique_together=set(),
        ),
    ]
