# Generated by Django 2.0.7 on 2018-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0029_auto_20181122_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isTable',
            field=models.BooleanField(default=False),
        ),
    ]
