# Generated by Django 2.0.7 on 2018-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='charpter',
            field=models.IntegerField(default=0),
        ),
    ]
