# Generated by Django 2.0.7 on 2018-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_content_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
