# Generated by Django 2.0.7 on 2018-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_content_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isTitle',
            field=models.BooleanField(default=False),
        ),
    ]
