# Generated by Django 2.0.7 on 2018-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180730_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.IntegerField(default=0),
        ),
    ]
