# Generated by Django 2.0.7 on 2018-07-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='code',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
