# Generated by Django 2.0.7 on 2018-08-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180802_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='code',
        ),
    ]
