# Generated by Django 2.0.7 on 2018-10-09 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20180803_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Fill_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='isSubTitle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fill',
            name='fill_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Fill_Answer'),
        ),
    ]
