# Generated by Django 2.0.7 on 2018-10-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20181009_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill',
            name='fill_answer',
        ),
    ]
