# Generated by Django 2.0.7 on 2018-10-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_fill_answer_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isImage',
            field=models.BooleanField(default=False),
        ),
    ]
