# Generated by Django 2.0.7 on 2018-11-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_fill_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isLink',
            field=models.BooleanField(default=False),
        ),
    ]
