# Generated by Django 2.0.7 on 2018-11-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20181106_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='number',
        ),
    ]
