# Generated by Django 2.0.7 on 2018-12-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20181107_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isTable',
            field=models.BooleanField(default=False),
        ),
    ]
