# Generated by Django 2.0.7 on 2018-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20181205_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
