# Generated by Django 2.0.7 on 2018-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20181205_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill',
            name='question',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
