# Generated by Django 2.0.7 on 2018-12-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_auto_20181205_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
