# Generated by Django 2.0.2 on 2018-04-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_title', models.CharField(max_length=50, null=True)),
                ('assessment_content', models.CharField(max_length=1000, null=True)),
                ('assessment_answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('ass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_content', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
