# Generated by Django 2.0.2 on 2018-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assessment_assessment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentcode',
            name='code',
        ),
        migrations.AddField(
            model_name='assessmentcode',
            name='codename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
