# Generated by Django 2.0.7 on 2018-07-16 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0003_auto_20180507_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assessment_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='assessmentcode',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='assessmentcode',
            name='codename',
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcode',
            unique_together={('ass', 'user')},
        ),
        migrations.AddField(
            model_name='havevote',
            name='ass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment'),
        ),
        migrations.AddField(
            model_name='havevote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='havevote',
            unique_together={('user', 'ass')},
        ),
    ]
