# Generated by Django 2.0.7 on 2018-07-23 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_auto_20180716_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='havevote',
            name='ass_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.AssessmentCode'),
        ),
        migrations.RemoveField(
            model_name='havevote',
            name='ass',
        ),
        migrations.AlterUniqueTogether(
            name='havevote',
            unique_together={('user', 'ass_code')},
        ),
    ]
