# Generated by Django 2.0.7 on 2018-08-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20180723_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
