# Generated by Django 2.0.7 on 2018-08-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_assessment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
