# Generated by Django 2.0.7 on 2018-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_auto_20180911_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentcode',
            name='code',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
